name: flutter_hot_reload
description: A cli tool to run Flutter applications and auto hot reload it when files are changed
version: 0.0.4
homepage: https://github.com/labulakalia/flutter_hot_reload

executables:
  flutter_hot_reload:

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  watcher: ^1.1.1
